# Generated by Django 4.2.5 on 2023-09-17 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('food_consuming', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consume',
            old_name='food',
            new_name='food_consumed',
        ),
    ]
